version: '3.7'

services:

  builder:
    image: ssh2lxd-builder
    build: docker
    restart: on-failure
    tty: true
    volumes: &vol
      - .:/root/build:cached
      - ./docker/bashrc:/root/.bashrc
      - ./docker/rpmmacros:/root/.rpmmacros
