# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

alias rpmbb='rpmbuild -bb'
alias rpmbs='rpmbuild -bs'
alias rpmrb='rpmbuild --rebuild'
alias yumi='dnf install -y'
alias yumr='dnf reinstall -y'
alias yume='dnf erase -y'
alias yumd='dnf downgrade -y'
alias yumbd='yum-builddep -y'
alias rpmsrc='spectool -R -g'
